openapi: 3.0.3
info:
  title: Parser API
  version: 3.0.0
servers:
  - url: http://localhost:8000
  # - url: http://155.212.187.80:8000
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
  /parse/yandex:
    post:
      parameters:
        - $ref: "#/components/parameters/CountParam"
        - $ref: "#/components/parameters/MinRatingParam"
        - $ref: "#/components/parameters/MaxRatingParam"
        - $ref: "#/components/parameters/DateStartParam"
        - $ref: "#/components/parameters/DateEndParam"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ParseRequest" }
      responses:
        "200":
          description: Parse result
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ParseResponse" }
  /parse/2gis:
    post:
      parameters:
        - $ref: "#/components/parameters/CountParam"
        - $ref: "#/components/parameters/MinRatingParam"
        - $ref: "#/components/parameters/MaxRatingParam"
        - $ref: "#/components/parameters/DateStartParam"
        - $ref: "#/components/parameters/DateEndParam"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ParseRequest" }
      responses:
        "200":
          description: Parse result
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ParseResponse" }
  /parse/doctors:
    post:
      parameters:
        - $ref: "#/components/parameters/CountParam"
        - $ref: "#/components/parameters/MinRatingParam"
        - $ref: "#/components/parameters/MaxRatingParam"
        - $ref: "#/components/parameters/DateStartParam"
        - $ref: "#/components/parameters/DateEndParam"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ParseRequest" }
      responses:
        "200":
          description: Parse result
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ParseResponse" }

components:
  schemas:
    ParseRequest:
      type: object
      required: [url]
      properties:
        url:
          type: string
    ParseResponse:
      type: object
      required: [success]
      properties:
        success: { type: boolean }
        data:
          nullable: true
          type: object
        error:
          nullable: true
          type: string
  parameters:
    CountParam:
      in: query
      name: count
      required: false
      schema:
        type: integer
        minimum: 0
        maximum: 150
      description: Сколько отзывов вернуть в ответе (в кеше хранится полный результат).

    MinRatingParam:
      in: query
      name: minRating
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 5

    MaxRatingParam:
      in: query
      name: maxRating
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 5

    DateStartParam:
      in: query
      name: dateStart
      required: false
      schema:
        type: string
        format: date
      description: YYYY-MM-DD

    DateEndParam:
      in: query
      name: dateEnd
      required: false
      schema:
        type: string
        format: date
      description: YYYY-MM-DD

